Fixed a ``NameError`` when attempting to catch ``FileNotFoundError`` on
Python 2.7.
